# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_trainresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainresult',
            name='image',
            field=models.CharField(max_length=128),
        ),
    ]
